// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark']
    }

    // Components re-exported with className support (resolved by metro at runtime)
    export {
        View,
        Text,
        ScrollView,
        TouchableOpacity,
        FlatList,
        TextInput,
        Pressable,
        Image,
        Modal,
        ActivityIndicator,
        Switch,
        TouchableHighlight,
        TouchableNativeFeedback,
        TouchableWithoutFeedback,
        KeyboardAvoidingView,
        SafeAreaView,
    } from 'react-native';
}

export {}
